# .github/workflows/keep-streamlit-alive.yml
name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # a cada 30 minutos
  workflow_dispatch:       # permite disparar manualmente

jobs:
  poke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Instalar Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Executar script Python
      run: python acorda_apps.py
