# .github/workflows/keep-streamlit-alive.yml
name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '0 */3 * * *'   # a cada 3 horas (00:00, 03:00, 06:00, etc.)
  workflow_dispatch:        # permite disparar manualmente

jobs:
  wake-apps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install playwright

    - name: Instalar browsers do Playwright
      run: |
        playwright install chromium

    - name: Executar script Python
      run: python acorda_apps.py